### ISSUE TITLE
Add Support for Scraping Job Details from Google Job Search URLs

### ISSUE THREAD

**Issue by 09Kanika** [iiakshat/google-jobs#1]
## Description:
Currently, the project supports scraping job details from Microsoft Bing's job search pages. It would be highly beneficial if the application could also support scraping job details from Google job search URLs.

**Proposed Enhancement:**
- Enable input of Google job search URLs.
- Implement scraping logic for job titles, companies, and locations from Google job search results.
- Ensure the output format remains consistent with the existing JSON structure.

**Rationale:**
Expanding the functionality to include Google job search will significantly increase the application's utility and user base, as many users prefer Google for job searches.

**Example URL for Testing:**
- Bing: `https://www.bing.com/jobs?q=ml+jobs&scp=0&rb=0&rc=20&L2=true&c=1&form=JOBL2S`
- Google: `https://www.google.com/search?q=ml+jobs`

**Additional Notes:**
This enhancement will likely require adjustments in the BeautifulSoup parsing logic to handle the different HTML structures of Google's job search results.

Thank you for considering this feature request.
```

**Comment by iiakshat** [comment]
Thanks @09Kanika for pointing out this issue. I am assigning this issue to you. Can you contribute?

**Comment by 09Kanika** [comment]
Yes, Sure!
